### ISSUE TITLE
Compilation Issue Ubuntu

### ISSUE THREAD

**Issue by tregua87** [kaist-ina/SGX-Tor#1]
Hi all!
I am trying to compile your project on an Ubuntu 18.10.

I just cloned the repo and run:

```
cd (rootdir)/Enclave/TrustedLibrary/LibEvent_SGX
./configure
make
```
But I get this error:
```
bufferevent_openssl.c:237:2: note: (near initialization for 'methods_bufferevent')
bufferevent_openssl.c:228:19: error: storage size of 'methods_bufferevent' isn't known
 static BIO_METHOD methods_bufferevent = {
```
Could you help me, please?

**Comment by inasmkim** [comment]
Hi, thanks for your contact.
I will check the repo and let you know.
Please let me know the version of sgx sdk that you use.

Thanks,
Seongmin

2019년 1월 20일 (일) 오전 3:54에 Flavio Toffalini <notifications@github.com>님이 작성:

**Comment by tregua87** [comment]
Hi!

I installed SGX SDK 2.2.
SDK and drives are installed in a separate directory. I hope this is not a problem.

**Comment by inasmkim** [comment]
Okay I will check and let you know after I fix this issue.

Thanks!
Seongmin

2019년 1월 20일 (일) 오후 6:34에 Flavio Toffalini <notifications@github.com>님이 작성:

**Comment by tregua87** [comment]
Hi @inasmkim 
did you manage to look for that error, please?

It looks like that we miss the definition of `BIO_METHOD` symbol.

I am grepping the code to find it but without results.

**Comment by infobiac** [comment]
Hi,

I'm wondering if this is still being worked on?

Thanks!

**Comment by inasmkim** [comment]
Hi, we fix this issue but we are currently working on adopting a new version of remote attestation API as we wrote in main page.
We believe you may use the new version of SGX-Tor in March.
Thanks!

**Comment by nabulator** [comment]
Hi, Running Ubuntu 18.04 with the almost same compilation error while trying to build LibEvent_SGX

`bufferevent_openssl.c:228:19: error: storage size of 'methods_bufferevent' isn't known static BIO_METHOD methods_bufferevent = {
`

I have installed the latest version of SGX: 2.6

Does your previous comment indicate that you fixed this issue or simply won't fix? Also you replied in March you will fix in March. Is this the same March?
